<?php

/*
 * COUNTRY LIST FOR LessonZone Post Attachment
 * Reminder: When Adding Additional Countries, Ensure That This 
 * Country is also added to table Data in 'lzPA-tableData.php' File!!!
 */


$lzPA_tableCountry = array( "English" 				=> array ( "Australia", "Canada", "Ireland", "New Zealand", "South Africa", "United Kingdom", "United States"), 
						 	"Spanish" 				=> array ( "Argentina", "Columbia", "Chile", "Mexico", "Peru", "Venezuala"),
							"French" 				=> array ( "France"),
							"Chinese" 				=> array ( "China", "Singapore", "Taiwan"),
							"ESL (Asia)" 		  	=> array ( "Hong Kong", "Indonesia", "Malaysia", "South Korea", "Thailand"),
							"ESL (Rest of World)" 	=> array ( "Italy", "Russia", "Spain", "Turkey"),
							"Hindi" 				=> array ( "India"),
							"Portugese" 			=> array ( "Brazil"),
							"German" 				=> array ( "Germany"),
							"Japanese" 				=> array ( "Japan" ) 
						);


$lzPA_fullCountry = array( "Afghanistan", 
							"Aland Islands", 
							"Albania", 
							"Algeria", 
							"American Samoa", 
							"Andorra", 
							"Angola", 
							"Anguilla", 
							"Antarctica", 
							"Antigua And Barbuda",
							"Argentina", 
							"Armenia", 
							"Aruba", 
							"Australia", 
							"Austria", 
							"Azerbaijan", 
							"Bahamas", 
							"Bahrain",
							"Bangladesh", 
							"Barbados", 
							"Belarus", 
							"Belgium", 
							"Belize", 
							"Benin", 
							"Bermuda", 
							"Bhutan", 
							"Bolivia", 
							"Bosnia And Herzegovina", 
							"Botswana", "Bouvet Island", 
							"Brazil", 
							"British Indian Ocean Territory", 
							"Brunei Darussalam", 
							"Bulgaria", 
							"Burkina Faso", 
							"Burundi", 
							"Cambodia", 
							"Cameroon", 
							"Canada", 
							"Cape Verde", 
							"Cayman Islands", 
							"Central African Republic", 
							"Chad", 
							"Chile", 
							"China", 
							"Christmas Island", 
							"Cocos (Keeling) Islands", 
							"Colombia", 
							"Comoros", 
							"Congo",
							"Congo", 
							"The Democratic Republic Of The", 
							"Cook Islands", 
							"Costa Rica", 
							"Cote D'ivoire", 
							"Croatia", 
							"Cuba", 
							"Cyprus", 
							"Czech Republic", 
							"Denmark", 
							"Djibouti", 
							"Dominica", 
							"Dominican Republic", 
							"Ecuador", 
							"Egypt",
							"El Salvador", 
							"Equatorial Guinea", 
							"Eritrea", 
							"Estonia", 
							"Ethiopia", 
							"Falkland Islands (Malvinas)", 
							"Faroe Islands", 
							"Fiji", 
							"Finland", 
							"France",
							"French Guiana", 
							"French Polynesia", 
							"French Southern Territories", 
							"Gabon", 
							"Gambia", 
							"Georgia", 
							"Germany", 
							"Ghana", 
							"Gibraltar", 
							"Greece", 
							"Greenland", 
							"Grenada", 
							"Guadeloupe", 
							"Guam", 
							"Guatemala", 
							"Guernsey", 
							"Guinea", 
							"Guinea-
							bissau", 
							"Guyana", 
							"Haiti", 
							"Heard Island And Mcdonald Islands", 
							"Holy See (Vatican City State)", 
							"Honduras", 
							"Hong Kong", 
							"Hungary", 
							"Iceland", 
							"India", 
							"Indonesia", 
							"Iran", 
							"Iraq", 
							"Ireland", 
							"Isle Of Man", 
							"Israel", 
							"Italy", 
							"Jamaica", 
							"Japan", 
							"Jersey", 
							"Jordan", 
							"Kazakhstan", 
							"Kenya", 
							"Kiribati", 
							"Korea, Democratic People's Republic Of", 
							"Korea, Republic Of", 
							"Kuwait", 
							"Kyrgyzstan", 
							"Lao", 
							"Latvia", 
							"Lebanon", 
							"Lesotho", 
							"Liberia", 
							"Libyan Arab Jamahiriya", 
							"Liechtenstein", 
							"Lithuania", 
							"Luxembourg", 
							"Macao", 
							"Macedonia", 
							"Madagascar", 
							"Malawi", 
							"Malaysia", 
							"Maldives", 
							"Mali", 
							"Malta", 
							"Marshall Islands", 
							"Martinique", 
							"Mauritania", 
							"Mauritius", 
							"Mayotte", 
							"Mexico", 
							"Micronesia, Federated States Of", 
							"Moldova", 
							"Monaco", 
							"Mongolia", 
							"Montenegro", 
							"Montserrat", 
							"Morocco", 
							"Mozambique", 
							"Myanmar", 
							"Namibia", 
							"Nauru", 
							"Nepal", 
							"Netherlands", 
							"Netherlands Antilles", 
							"New Caledonia", 
							"New Zealand", 
							"Nicaragua", 
							"Niger", 
							"Nigeria", 
							"Niue", 
							"Norfolk Island", 
							"Northern Mariana Islands", 
							"Norway", 
							"Oman", 
							"Pakistan", 
							"Palau", 
							"Palestinian Territory", 
							"Panama", 
							"Papua New Guinea", 
							"Paraguay", 
							"Peru", 
							"Philippines", 
							"Pitcairn", 
							"Poland", 
							"Portugal", 
							"Puerto Rico", 
							"Qatar", 
							"Reunion", 
							"Romania", 
							"Russian Federation", 
							"Rwanda", 
							"Saint Helena", 
							"Saint Kitts And Nevis", 
							"Saint Lucia", 
							"Saint Pierre And Miquelon", 
							"Saint Vincent And The Grenadines", 
							"Samoa", 
							"San Marino", 
							"Sao Tome And Principe", 
							"Saudi Arabia", 
							"Senegal", 
							"Serbia", 
							"Seychelles", 
							"Sierra Leone", 
							"Singapore", 
							"Slovakia", 
							"Slovenia", 
							"Solomon Islands", 
							"Somalia", 
							"South Africa", 
							"South Georgia And The South Sandwich Islands", 
							"Spain", 
							"Sri Lanka", 
							"Sudan", 
							"Suriname", 
							"Svalbard And Jan Mayen", 
							"Swaziland", 
							"Sweden", 
							"Switzerland", 
							"Syrian Arab Republic", 
							"Taiwan", 
							"Tajikistan", 
							"Tanzania", 
							"Thailand", 
							"Timor-leste", 
							"Togo", 
							"Tokelau", 
							"Tonga", 
							"Trinidad And Tobago", 
							"Tunisia", 
							"Turkey", 
							"Turkmenistan", 
							"Turks And Caicos Islands", 
							"Tuvalu", 
							"Uganda", 
							"Ukraine", 
							"United Arab Emirates", 
							"United Kingdom", 
							"United States", 
							"United States Minor Outlying Islands", 
							"Uruguay", 
							"Uzbekistan", 
							"Vanuatu", 
							"Venezuela", 
							"Viet Nam", 
							"Virgin Islands, British", 
							"Virgin Islands, U.S.", 
							"Wallis And Futuna", 
							"Western Sahara", 
							"Yemen", 
							"Zambia", 
							"Zimbabwe" );
			
			
?>