function reset_theme_1() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = 'A6BA7D';
    document.getElementById('bg_bottom').value = 'FDFCDE';
    document.getElementById('border_color').value = '000000';	
    document.getElementById('text_color_month').value = '080808';
    document.getElementById('text_color_week_days').value = '000000';	
    document.getElementById('text_color_other_months').value = '6E5959';
    document.getElementById('text_color_this_month_unevented').value = '060D12';
    document.getElementById('text_color_this_month_evented').value = '000000';
    document.getElementById('event_title_color').value = '000000';
    document.getElementById('current_day_border_color').value = '4AFF9E';
    document.getElementById('bg_color_this_month_evented').value = 'FF6933';
    document.getElementById('next_prev_event_arrowcolor').value = 'E0E0C5';
    document.getElementById('show_event_bgcolor').value = 'FDFCDE';
    document.getElementById('cell_border_color').value = '000000';
    document.getElementById('week_days_cell_height').value = '50';
    document.getElementById('arrow_color_month').value = '000000';
    document.getElementById('text_color_sun_days').value = 'FF0000';
    document.getElementById('title_color').value = '000000';
    document.getElementById('next_prev_event_bgcolor').value = 'CCCCCC';
    document.getElementById('title_font_size').value = '18';
    document.getElementById('title_font').value = 'Courier New';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = '000000';
    document.getElementById('date_size').value = '16';
    document.getElementById('date_font').value = 'Courier New';
    document.getElementById('date_style').value = 'bold';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '600';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '18';
    document.getElementById('other_days_font_size').value = '12';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '2';
    document.getElementById('top_height').value = '90';
    document.getElementById('bg_color_other_months').value = 'FFFFFF';
    document.getElementById('sundays_bg_color').value = 'FDFCDE';
    document.getElementById('weekdays_bg_color').value = 'E6E6DE';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'BD848A';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'A6BA7C';
    document.getElementById('event_bg_color1').value = 'FDFCDE';
    document.getElementById('event_bg_color2').value = 'FDFCDE';
    document.getElementById('event_num_bg_color1').value = 'FDFCDE';
    document.getElementById('event_num_bg_color2').value = 'FDFCDE';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = '474747';
    document.getElementById('week_font_color').value = 'FFFFFF';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'E8E7CC';
	document.getElementById('ev_title_bg_color').value = 'FF6933';
	document.getElementById('views_tabs_text_color').value = '000000';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_2() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '80';
    document.getElementById('bg_top').value = '36A7E9';
    document.getElementById('bg_bottom').value = 'FFFFFF';
    document.getElementById('border_color').value = '000000';
    document.getElementById('text_color_month').value = '000000';
    document.getElementById('text_color_week_days').value = '000000';
    document.getElementById('text_color_other_months').value = '525252';
    document.getElementById('text_color_this_month_unevented').value = '000000';
    document.getElementById('text_color_this_month_evented').value = 'FFFFFF';
    document.getElementById('event_title_color').value = '000000';
    document.getElementById('current_day_border_color').value = '36A7E9';
    document.getElementById('bg_color_this_month_evented').value = 'FFA142';
    document.getElementById('next_prev_event_arrowcolor').value = 'FFFFFF';
    document.getElementById('show_event_bgcolor').value = '36A7E9';
    document.getElementById('cell_border_color').value = '000000';
    document.getElementById('week_days_cell_height').value = '40';
    document.getElementById('arrow_color_month').value = '000000';
    document.getElementById('text_color_sun_days').value = '36A7E9';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = 'FFA142';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '16';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'bold';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '600';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '20';
    document.getElementById('other_days_font_size').value = '20';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '4';
    document.getElementById('top_height').value = '80';
    document.getElementById('bg_color_other_months').value = 'FFFFFF';
    document.getElementById('sundays_bg_color').value = 'FFFFFF';
    document.getElementById('weekdays_bg_color').value = 'FFFFFF';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'FFFFFF';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'FFA041';
    document.getElementById('event_bg_color1').value = 'FFFFFF';
    document.getElementById('event_bg_color2').value = 'FFFFFF';
    document.getElementById('event_num_bg_color1').value = 'FFFFFF';
    document.getElementById('event_num_bg_color2').value = 'FFFFFF';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = '6E6E6E';
    document.getElementById('week_font_color').value = 'FFFFFF';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'FFA142';
	document.getElementById('ev_title_bg_color').value = 'FFA142';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_3() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '00004F';
    document.getElementById('bg_bottom').value = '5BCAFF';
    document.getElementById('border_color').value = '000000';
    document.getElementById('text_color_month').value = 'D1D4F5';
    document.getElementById('text_color_week_days').value = 'FFFFFF';
    document.getElementById('text_color_other_months').value = 'E6E6E6';
    document.getElementById('text_color_this_month_unevented').value = '000000';
    document.getElementById('text_color_this_month_evented').value = 'FFFFFF';
    document.getElementById('event_title_color').value = '050505';
    document.getElementById('current_day_border_color').value = 'FFFFFF';
    document.getElementById('bg_color_this_month_evented').value = 'DEDEDE';
    document.getElementById('next_prev_event_arrowcolor').value = 'FFFFFF';
    document.getElementById('show_event_bgcolor').value = '009EEB';
    document.getElementById('cell_border_color').value = '000000';
    document.getElementById('week_days_cell_height').value = '30';
    document.getElementById('arrow_color_month').value = 'FFFFFF';
    document.getElementById('text_color_sun_days').value = '000000';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '00004F';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '18';
    document.getElementById('other_days_font_size').value = '14';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '2';
    document.getElementById('top_height').value = '120';
    document.getElementById('bg_color_other_months').value = 'C0C0C0';
    document.getElementById('sundays_bg_color').value = '8ADAFF';
    document.getElementById('weekdays_bg_color').value = '000000';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = '000000';
    document.getElementById('border_radius').value = '';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = '5BCAFF';
    document.getElementById('event_bg_color1').value = 'FFFFFF';
    document.getElementById('event_bg_color2').value = 'FFFFFF';
    document.getElementById('event_num_bg_color1').value = 'FFFFFF';
    document.getElementById('event_num_bg_color2').value = 'FFFFFF';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = 'FFFFFF';
    document.getElementById('week_font_color').value = 'FFFFFF';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = '5BCAFF';
	document.getElementById('ev_title_bg_color').value = 'DEDEDE';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_4() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '2A2829';
    document.getElementById('bg_bottom').value = '323232';
    document.getElementById('border_color').value = '000000';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = 'FFFFFF';
    document.getElementById('text_color_other_months').value = 'FFFFFF';
    document.getElementById('text_color_this_month_unevented').value = 'FFFFFF';
    document.getElementById('text_color_this_month_evented').value = '000000';
    document.getElementById('event_title_color').value = '000000';
    document.getElementById('current_day_border_color').value = 'FFFFFF';
    document.getElementById('bg_color_this_month_evented').value = 'F0F0F0';
    document.getElementById('next_prev_event_arrowcolor').value = 'C7C7C7';
    document.getElementById('show_event_bgcolor').value = '969696';
    document.getElementById('cell_border_color').value = '000000';
    document.getElementById('week_days_cell_height').value = '35';
    document.getElementById('arrow_color_month').value = 'FFFFFF';
    document.getElementById('text_color_sun_days').value = 'FFFFFF';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '323232';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '16';
    document.getElementById('other_days_font_size').value = '12';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '2';
    document.getElementById('top_height').value = '90';
    document.getElementById('bg_color_other_months').value = '282828';
    document.getElementById('sundays_bg_color').value = '323232';
    document.getElementById('weekdays_bg_color').value = '969696';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = '969696';
    document.getElementById('border_radius').value = '8';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = '969696';
    document.getElementById('event_bg_color1').value = '323232';
    document.getElementById('event_bg_color2').value = '323232';
    document.getElementById('event_num_bg_color1').value = '323232';
    document.getElementById('event_num_bg_color2').value = '323232';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = 'FFFFFF';
    document.getElementById('week_font_color').value = 'FFFFFF';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = '969696';
	document.getElementById('ev_title_bg_color').value = 'F0F0F0';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}
function reset_theme_5() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '9A0000';
    document.getElementById('bg_bottom').value = 'CDCC96';
    document.getElementById('border_color').value = 'E6E6E4';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = '000000';
    document.getElementById('text_color_other_months').value = '525252';
    document.getElementById('text_color_this_month_unevented').value = '000000';
    document.getElementById('text_color_this_month_evented').value = 'FFFFFF';
    document.getElementById('event_title_color').value = 'FFFFFF';
    document.getElementById('current_day_border_color').value = '9A0000';
    document.getElementById('bg_color_this_month_evented').value = '9A0000';
    document.getElementById('next_prev_event_arrowcolor').value = 'DEDDB5';
    document.getElementById('show_event_bgcolor').value = 'FFFED0';
    document.getElementById('cell_border_color').value = 'FFFFFF';
    document.getElementById('week_days_cell_height').value = '60';
    document.getElementById('arrow_color_month').value = 'FFFFFF';
    document.getElementById('text_color_sun_days').value = '000000';
    document.getElementById('title_color').value = '000000';
    document.getElementById('next_prev_event_bgcolor').value = '9A0000';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = '000000';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '18';
    document.getElementById('other_days_font_size').value = '';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '18';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'E4E7CC';
    document.getElementById('sundays_bg_color').value = 'CDCC96';
    document.getElementById('weekdays_bg_color').value = 'FFFED0';
    document.getElementById('week_start_day').value = 'mo';
    document.getElementById('weekday_sunday_bg_color').value = 'FFFED0';
    document.getElementById('border_radius').value = '6';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'E4E7CC';
    document.getElementById('event_bg_color1').value = 'CECD97';
    document.getElementById('event_bg_color2').value = 'CECD97';
    document.getElementById('event_num_bg_color1').value = 'CECD97';
    document.getElementById('event_num_bg_color2').value = 'CECD97';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = '8F8F8F';
    document.getElementById('week_font_color').value = '000000';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'CDCC96';
	document.getElementById('ev_title_bg_color').value = '9A0000';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_6() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = 'FCF7D9';
    document.getElementById('bg_bottom').value = 'FFFFFF';
    document.getElementById('border_color').value = '3DBCEB';
    document.getElementById('text_color_month').value = '9A0000';
    document.getElementById('text_color_week_days').value = 'FFFFFF';
    document.getElementById('text_color_other_months').value = 'C7C7C7';
    document.getElementById('text_color_this_month_unevented').value = '1374C3';
    document.getElementById('text_color_this_month_evented').value = '000000';
    document.getElementById('event_title_color').value = '000000';
    document.getElementById('current_day_border_color').value = '9A0000';
    document.getElementById('bg_color_this_month_evented').value = 'FCF7D9';
    document.getElementById('next_prev_event_arrowcolor').value = 'E0E0E0';
    document.getElementById('show_event_bgcolor').value = 'FCF7D9';
    document.getElementById('cell_border_color').value = '1374C3';
    document.getElementById('week_days_cell_height').value = '20';
    document.getElementById('arrow_color_month').value = '9A0000';
    document.getElementById('text_color_sun_days').value = '013A7D';
    document.getElementById('title_color').value = '000000';
    document.getElementById('next_prev_event_bgcolor').value = '21B5FF';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = '000000';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'bold';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '16';
    document.getElementById('other_days_font_size').value = '12';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '12';
    document.getElementById('top_height').value = '93';
    document.getElementById('bg_color_other_months').value = 'FFFFFF';
    document.getElementById('sundays_bg_color').value = 'FFFFFF';
    document.getElementById('weekdays_bg_color').value = '013A7D';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = '1374C3';
    document.getElementById('border_radius').value = '6';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = '3CBBEB';
    document.getElementById('event_bg_color1').value = 'FFFFFF';
    document.getElementById('event_bg_color2').value = 'FFFFFF';
    document.getElementById('event_num_bg_color1').value = 'FCF7D9';
    document.getElementById('event_num_bg_color2').value = 'FFFFFF';
    document.getElementById('event_num_color').value = '970000';
    document.getElementById('day_month_font_color').value = 'FBE6E6';
    document.getElementById('week_font_color').value = 'FFFFFF';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
     document.getElementById('ev_title_bg_color').value = 'CFCBB2';
    document.getElementById('views_tabs_bg_color').value = '3DBCEB';
	document.getElementById('views_tabs_text_color').value = '000000';
	document.getElementById('views_tabs_font_size').value = '';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_7() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '598923';
    document.getElementById('bg_bottom').value = 'F0F0E6';
    document.getElementById('border_color').value = 'D78B29';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = '000000';
    document.getElementById('text_color_other_months').value = 'A6A6A6';
    document.getElementById('text_color_this_month_unevented').value = '5C5C5C';
    document.getElementById('text_color_this_month_evented').value = 'FFFFFF';
    document.getElementById('event_title_color').value = '000000';
    document.getElementById('current_day_border_color').value = '000000';
    document.getElementById('bg_color_this_month_evented').value = 'D78B29';
    document.getElementById('next_prev_event_arrowcolor').value = 'D78B29';
    document.getElementById('show_event_bgcolor').value = 'FFB061';
    document.getElementById('cell_border_color').value = '363636';
    document.getElementById('week_days_cell_height').value = '30';
    document.getElementById('arrow_color_month').value = 'FFFFFF';
    document.getElementById('text_color_sun_days').value = '000000';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = 'DDDCC8';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = 'Courier New';
    document.getElementById('title_style').value = 'bold';
    document.getElementById('date_color').value = '000000';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '16';
    document.getElementById('other_days_font_size').value = '12';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '12';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'DDDCC8';
    document.getElementById('sundays_bg_color').value = 'F0F0E6';
    document.getElementById('weekdays_bg_color').value = 'D78B29';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'D78B29';
    document.getElementById('border_radius').value = '6';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = '588922';
    document.getElementById('event_bg_color1').value = 'F0F0E6';
    document.getElementById('event_bg_color2').value = 'F0F0E6';
    document.getElementById('event_num_bg_color1').value = 'F0F0E6';
    document.getElementById('event_num_bg_color2').value = 'F0F0E6';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = 'FFFFFF';
    document.getElementById('week_font_color').value = 'FFFFFF';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'D78B29';
	document.getElementById('ev_title_bg_color').value = 'D78B29';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_8() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '009898';
    document.getElementById('bg_bottom').value = 'FDFDCC';
    document.getElementById('border_color').value = 'FDFDCC';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = '000000';
    document.getElementById('text_color_other_months').value = '8C8C8C';
    document.getElementById('text_color_this_month_unevented').value = '383838';
    document.getElementById('text_color_this_month_evented').value = '383838';
    document.getElementById('event_title_color').value = '000000';
    document.getElementById('current_day_border_color').value = '000000';
    document.getElementById('bg_color_this_month_evented').value = 'FE7C00';
    document.getElementById('next_prev_event_arrowcolor').value = 'FEAC30';
    document.getElementById('show_event_bgcolor').value = 'FE7C00';
    document.getElementById('cell_border_color').value = '4D4D4D';
    document.getElementById('week_days_cell_height').value = '30';
    document.getElementById('arrow_color_month').value = 'FFFFFF';
    document.getElementById('text_color_sun_days').value = '000000';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = 'FDFDE8';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '16';
    document.getElementById('other_days_font_size').value = '12';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '14';
    document.getElementById('top_height').value = '90';
    document.getElementById('bg_color_other_months').value = 'FDFDE8';
    document.getElementById('sundays_bg_color').value = 'BACBDC';
    document.getElementById('weekdays_bg_color').value = '9865FE';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = '9865FE';
    document.getElementById('border_radius').value = '2';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = '9765FD';
    document.getElementById('event_bg_color1').value = 'FDFCCC';
    document.getElementById('event_bg_color2').value = 'FDFCCC';
    document.getElementById('event_num_bg_color1').value = 'FDFCCC';
    document.getElementById('event_num_bg_color2').value = 'FDFCCC';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = 'FFFFFF';
    document.getElementById('week_font_color').value = 'FFFFFF';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'FDFDCC';
	document.getElementById('ev_title_bg_color').value = 'FE7C00';
	document.getElementById('views_tabs_text_color').value = '000000';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_9() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '346699';
    document.getElementById('bg_bottom').value = 'E3F9F9';
    document.getElementById('border_color').value = '346699';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = 'FFFFFF';
    document.getElementById('text_color_other_months').value = 'FFFFFF';
    document.getElementById('text_color_this_month_unevented').value = '2410EE';
    document.getElementById('text_color_this_month_evented').value = '000000';
    document.getElementById('event_title_color').value = '000000';
    document.getElementById('current_day_border_color').value = '346699';
    document.getElementById('bg_color_this_month_evented').value = 'FFCC33';
    document.getElementById('next_prev_event_arrowcolor').value = 'E3B62D';
    document.getElementById('show_event_bgcolor').value = 'FFCC33';
    document.getElementById('cell_border_color').value = '6B6B6B';
    document.getElementById('week_days_cell_height').value = '25';
    document.getElementById('arrow_color_month').value = 'FFFFFF';
    document.getElementById('text_color_sun_days').value = '2410EE';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '346699';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = '000000';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '18';
    document.getElementById('other_days_font_size').value = '14';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '10';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'CCCCCC';
    document.getElementById('sundays_bg_color').value = 'CDDDFF';
    document.getElementById('weekdays_bg_color').value = '68676D';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = '68676D';
    document.getElementById('border_radius').value = '4';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'E3F8FA';
    document.getElementById('event_bg_color1').value = 'CCCCCC';
    document.getElementById('event_bg_color2').value = 'CCCCCC';
    document.getElementById('event_num_bg_color1').value = 'CCCCCC';
    document.getElementById('event_num_bg_color2').value = 'CCCCCC';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = '726ED6';
    document.getElementById('week_font_color').value = '726ED6';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'CDDDFF';
	document.getElementById('ev_title_bg_color').value = 'FFCC33';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_10() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = 'C0EFC0';
    document.getElementById('bg_bottom').value = 'E3F9F9';
    document.getElementById('border_color').value = 'ABCEA8';
    document.getElementById('text_color_month').value = '58A42B';
    document.getElementById('text_color_week_days').value = '000000';
    document.getElementById('text_color_other_months').value = 'B0B0B0';
    document.getElementById('text_color_this_month_unevented').value = '383838';
    document.getElementById('text_color_this_month_evented').value = '383838';
    document.getElementById('event_title_color').value = '383838';
    document.getElementById('current_day_border_color').value = '58A42B';
    document.getElementById('bg_color_this_month_evented').value = 'C0EFC0';
    document.getElementById('next_prev_event_arrowcolor').value = 'AED9AE';
    document.getElementById('show_event_bgcolor').value = 'C0EFC0';
    document.getElementById('cell_border_color').value = 'B1B1B0';
    document.getElementById('week_days_cell_height').value = '25';
    document.getElementById('arrow_color_month').value = '58A42B';
    document.getElementById('text_color_sun_days').value = 'FF7C5C';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '58A42B';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = '262626';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '600';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '16';
    document.getElementById('other_days_font_size').value = '12';
    document.getElementById('weekdays_font_size').value = '12';
    document.getElementById('border_width').value = '8';
    document.getElementById('top_height').value = '40';
    document.getElementById('bg_color_other_months').value = 'E1DDE9';
    document.getElementById('sundays_bg_color').value = 'FFFFFF';
    document.getElementById('weekdays_bg_color').value = 'FFFFFF';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'FFFFFF';
    document.getElementById('border_radius').value = '2';
    document.getElementById('month_font_size').value = '20';
    document.getElementById('arrow_size').value = '20';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'DFDDE7';
    document.getElementById('event_bg_color1').value = 'E4F9FA';
    document.getElementById('event_bg_color2').value = 'E4F9FA';
    document.getElementById('event_num_bg_color1').value = 'FFFFFF';
    document.getElementById('event_num_bg_color2').value = 'FFFFFF';
    document.getElementById('event_num_color').value = '000000';
    document.getElementById('day_month_font_color').value = '7DAC84';
    document.getElementById('week_font_color').value = '7DAC84';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'E3F9F9';
	document.getElementById('ev_title_bg_color').value = 'C0EFC0';
	document.getElementById('views_tabs_text_color').value = '000000';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_11() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = 'E7C892';
    document.getElementById('bg_bottom').value = '7E5F43';
    document.getElementById('border_color').value = 'FFC219';
    document.getElementById('text_color_month').value = '404040';
    document.getElementById('text_color_week_days').value = '404040';
    document.getElementById('text_color_other_months').value = 'FFFFFF';
    document.getElementById('text_color_this_month_unevented').value = 'FFFFFF';
    document.getElementById('text_color_this_month_evented').value = '404040';
    document.getElementById('event_title_color').value = '404040';
    document.getElementById('current_day_border_color').value = 'FFFFFF';
    document.getElementById('bg_color_this_month_evented').value = 'FFC219';
    document.getElementById('next_prev_event_arrowcolor').value = 'B3875F';
    document.getElementById('show_event_bgcolor').value = '7E5F43';
    document.getElementById('cell_border_color').value = '000000';
    document.getElementById('week_days_cell_height').value = '30';
    document.getElementById('arrow_color_month').value = '404040';
    document.getElementById('text_color_sun_days').value = 'FFFFFF';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = 'FFC219';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '2';
    document.getElementById('sundays_font_size').value = '18';
    document.getElementById('other_days_font_size').value = '12';
    document.getElementById('weekdays_font_size').value = '14';
    document.getElementById('border_width').value = '10';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = '523F30';
    document.getElementById('sundays_bg_color').value = '7E5F43';
    document.getElementById('weekdays_bg_color').value = 'FFC219';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'FFC219';
    document.getElementById('border_radius').value = '6';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'FFC11A';
    document.getElementById('event_bg_color1').value = '7E5F43';
    document.getElementById('event_bg_color2').value = '7E5F43';
    document.getElementById('event_num_bg_color1').value = '7E5F43';
    document.getElementById('event_num_bg_color2').value = '523F31';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = '4F3A11';
    document.getElementById('week_font_color').value = '4F3A11';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '15';
    document.getElementById('event_table_height').value = '25';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '13';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('views_tabs_bg_color').value = 'FFC219';
	document.getElementById('ev_title_bg_color').value = 'FFC219';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_12() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '65';
    document.getElementById('bg_top').value = '520017';
    document.getElementById('bg_bottom').value = 'E1E1E1';
    document.getElementById('border_color').value = 'ABCEA8';
    document.getElementById('text_color_month').value = 'FEFCFC';
    document.getElementById('text_color_week_days').value = '2A674D';
    document.getElementById('text_color_other_months').value = '817F7F';
    document.getElementById('text_color_this_month_unevented').value = '817F7F';
    document.getElementById('text_color_this_month_evented').value = '817F7F';
    document.getElementById('event_title_color').value = '292929';
    document.getElementById('current_day_border_color').value = '520017';
    document.getElementById('bg_color_this_month_evented').value = 'B69DA4';
    document.getElementById('next_prev_event_arrowcolor').value = 'B69DA4';
    document.getElementById('show_event_bgcolor').value = 'C5B1B6';
    document.getElementById('cell_border_color').value = 'B1B1B0';
    document.getElementById('week_days_cell_height').value = '50';
    document.getElementById('arrow_color_month').value = 'D0D0D0';
    document.getElementById('text_color_sun_days').value = '817F7F';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '997783';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = '262626';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '23';
    document.getElementById('other_days_font_size').value = '23';
    document.getElementById('weekdays_font_size').value = '20';
    document.getElementById('border_width').value = '0';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'E1E1E1';
    document.getElementById('sundays_bg_color').value = 'E1E1E1';
    document.getElementById('weekdays_bg_color').value = 'E1E1E1';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'BBBBBB';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'D6D5D5';
    document.getElementById('event_bg_color1').value = 'E1E1E1';
    document.getElementById('event_bg_color2').value = 'E1E1E1';
    document.getElementById('event_num_bg_color1').value = '450013';
    document.getElementById('event_num_bg_color2').value = '5A011A';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = '747474';
    document.getElementById('week_font_color').value = '400012';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '13';
    document.getElementById('event_table_height').value = '30';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '12';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('ev_title_bg_color').value = 'C5B1B6';
    document.getElementById('views_tabs_bg_color').value = '860126';
	document.getElementById('ev_title_bg_color').value = 'C5B1B6';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_13() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '005478';
    document.getElementById('bg_bottom').value = 'E1E1E1';
    document.getElementById('border_color').value = '005478';
    document.getElementById('text_color_month').value = 'F9F2F4';
    document.getElementById('text_color_week_days').value = '005D78';
    document.getElementById('text_color_other_months').value = 'B0B0B0';
    document.getElementById('text_color_this_month_unevented').value = '6A6A6A';
    document.getElementById('text_color_this_month_evented').value = '6A6A6A';
    document.getElementById('event_title_color').value = '236283';
    document.getElementById('current_day_border_color').value = '005478';
    document.getElementById('bg_color_this_month_evented').value = 'B4C5CC';
    document.getElementById('next_prev_event_arrowcolor').value = '97A0A6';
    document.getElementById('show_event_bgcolor').value = 'B4C5CC';
    document.getElementById('cell_border_color').value = 'A9A9A9';
    document.getElementById('week_days_cell_height').value = '50';
    document.getElementById('arrow_color_month').value = 'CCD1D2';
    document.getElementById('text_color_sun_days').value = '6A6A6A';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '00608A';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = '262626';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '1';
    document.getElementById('sundays_font_size').value = '25';
    document.getElementById('other_days_font_size').value = '25';
    document.getElementById('weekdays_font_size').value = '25';
    document.getElementById('border_width').value = '0';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'E1E1E1';
    document.getElementById('sundays_bg_color').value = 'E1E1E1';
    document.getElementById('weekdays_bg_color').value = 'D6D6D6';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'B5B5B5';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'D6D4D5';
    document.getElementById('event_bg_color1').value = 'E1E1E1';
    document.getElementById('event_bg_color2').value = 'DEDCDD';
    document.getElementById('event_num_bg_color1').value = '005478';
    document.getElementById('event_num_bg_color2').value = '006E91';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = '737373';
    document.getElementById('week_font_color').value = '005476';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '13';
    document.getElementById('event_table_height').value = '30';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '12';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('ev_title_bg_color').value = 'C3D0D6';
    document.getElementById('views_tabs_bg_color').value = '01799C';
	document.getElementById('ev_title_bg_color').value = 'C3D0D6';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_14() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '00512F';
    document.getElementById('bg_bottom').value = 'E1E1E1';
    document.getElementById('border_color').value = '005478';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = '175E41';
    document.getElementById('text_color_other_months').value = 'B0B0B0';
    document.getElementById('text_color_this_month_unevented').value = '9A9898';
    document.getElementById('text_color_this_month_evented').value = '9A9898';
    document.getElementById('event_title_color').value = '383838';
    document.getElementById('current_day_border_color').value = '00502F';
    document.getElementById('bg_color_this_month_evented').value = '9DB5AB';
    document.getElementById('next_prev_event_arrowcolor').value = '9DB5AB';
    document.getElementById('show_event_bgcolor').value = 'B1C4BC';
    document.getElementById('cell_border_color').value = 'B1B1B0';
    document.getElementById('week_days_cell_height').value = '50';
    document.getElementById('arrow_color_month').value = 'CFD2CF';
    document.getElementById('text_color_sun_days').value = '9A9898';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '175E41';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '2';
    document.getElementById('sundays_font_size').value = '25';
    document.getElementById('other_days_font_size').value = '25';
    document.getElementById('weekdays_font_size').value = '20';
    document.getElementById('border_width').value = '0';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'E1E1E1';
    document.getElementById('sundays_bg_color').value = 'E1E1E1';
    document.getElementById('weekdays_bg_color').value = 'E0E0E0';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'BBBBBB';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'D6D5D5';
    document.getElementById('event_bg_color1').value = 'E1E1E1';
    document.getElementById('event_bg_color2').value = 'DEDDDD';
    document.getElementById('event_num_bg_color1').value = '003C23';
    document.getElementById('event_num_bg_color2').value = '00502F';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = '747474';
    document.getElementById('week_font_color').value = '003D24';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '13';
    document.getElementById('event_table_height').value = '30';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '12';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('ev_title_bg_color').value = 'B1C4BC';
    document.getElementById('views_tabs_bg_color').value = '00882A';
	document.getElementById('ev_title_bg_color').value = 'B1C4BC';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_15() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = 'D57E01';
    document.getElementById('bg_bottom').value = 'E1E1E1';
    document.getElementById('border_color').value = '005478';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = '015130';
    document.getElementById('text_color_other_months').value = 'B0B0B0';
    document.getElementById('text_color_this_month_unevented').value = '7C7A7A';
    document.getElementById('text_color_this_month_evented').value = '7C7A7A';
    document.getElementById('event_title_color').value = '383838';
    document.getElementById('current_day_border_color').value = 'D57E01';
    document.getElementById('bg_color_this_month_evented').value = 'DDC39D';
    document.getElementById('next_prev_event_arrowcolor').value = 'E4CFB1';
    document.getElementById('show_event_bgcolor').value = 'DDC39D';
    document.getElementById('cell_border_color').value = 'B1B1B0';
    document.getElementById('week_days_cell_height').value = '50';
    document.getElementById('arrow_color_month').value = 'E1E2D9';
    document.getElementById('text_color_sun_days').value = '7C7A7A';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = 'D37D00';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '2';
    document.getElementById('sundays_font_size').value = '25';
    document.getElementById('other_days_font_size').value = '25';
    document.getElementById('weekdays_font_size').value = '20';
    document.getElementById('border_width').value = '0';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'E1DDE9';
    document.getElementById('sundays_bg_color').value = 'E1E1E1';
    document.getElementById('weekdays_bg_color').value = 'E1E1E1';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'BBBBBB';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'D6D5D5';
    document.getElementById('event_bg_color1').value = 'E1E1E1';
    document.getElementById('event_bg_color2').value = 'DEDDDD';
    document.getElementById('event_num_bg_color1').value = 'AB6501';
    document.getElementById('event_num_bg_color2').value = 'D57E01';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = '838383';
    document.getElementById('week_font_color').value = 'A26001';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '13';
    document.getElementById('event_table_height').value = '30';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '12';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('ev_title_bg_color').value = 'E4CFB1';
    document.getElementById('views_tabs_bg_color').value = 'E0AD01';
	document.getElementById('ev_title_bg_color').value = 'E4CFB1';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_16() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = 'FEA2EC';
    document.getElementById('bg_bottom').value = 'E1E1E1';
    document.getElementById('border_color').value = '005478';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = '00502F';
    document.getElementById('text_color_other_months').value = 'B0B0B0';
    document.getElementById('text_color_this_month_unevented').value = '817F7F';
    document.getElementById('text_color_this_month_evented').value = '817F7F';
    document.getElementById('event_title_color').value = '383838';
    document.getElementById('current_day_border_color').value = 'FEA2EC';
    document.getElementById('bg_color_this_month_evented').value = 'EACEE4';
    document.getElementById('next_prev_event_arrowcolor').value = 'EED8E9';
    document.getElementById('show_event_bgcolor').value = 'EACEE4';
    document.getElementById('cell_border_color').value = 'B1B1B0';
    document.getElementById('week_days_cell_height').value = '50';
    document.getElementById('arrow_color_month').value = 'D1D1D1';
    document.getElementById('text_color_sun_days').value = '817F7F';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = 'FA9FE8';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '2';
    document.getElementById('sundays_font_size').value = '25';
    document.getElementById('other_days_font_size').value = '25';
    document.getElementById('weekdays_font_size').value = '20';
    document.getElementById('border_width').value = '0';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'E1E1E1';
    document.getElementById('sundays_bg_color').value = 'E1E1E1';
    document.getElementById('weekdays_bg_color').value = 'D6D6D6';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'B5B5B5';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'D6D5D5';
    document.getElementById('event_bg_color1').value = 'E1E1E1';
    document.getElementById('event_bg_color2').value = 'DEDDDD';
    document.getElementById('event_num_bg_color1').value = 'C17BB4';
    document.getElementById('event_num_bg_color2').value = 'FCA0EA';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = '999898';
    document.getElementById('week_font_color').value = 'BD78B0';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '13';
    document.getElementById('event_table_height').value = '30';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '12';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('ev_title_bg_color').value = 'EED8E9';
    document.getElementById('views_tabs_bg_color').value = 'FDC5F2';
	document.getElementById('ev_title_bg_color').value = 'EED8E9';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_17() {
  if (confirm('Do you really want to reset theme?')) {
    document.getElementById('width').value = '700';
    document.getElementById('cell_height').value = '70';
    document.getElementById('bg_top').value = '52004F';
    document.getElementById('bg_bottom').value = 'E1E1E1';
    document.getElementById('border_color').value = '005478';
    document.getElementById('text_color_month').value = 'FFFFFF';
    document.getElementById('text_color_week_days').value = '00502F';
    document.getElementById('text_color_other_months').value = 'B0B0B0';
    document.getElementById('text_color_this_month_unevented').value = '817F7F';
    document.getElementById('text_color_this_month_evented').value = '817F7F';
    document.getElementById('event_title_color').value = '383838';
    document.getElementById('current_day_border_color').value = '52004F';
    document.getElementById('bg_color_this_month_evented').value = 'B69DB5';
    document.getElementById('next_prev_event_arrowcolor').value = 'C5B1C4';
    document.getElementById('show_event_bgcolor').value = 'B69DB5';
    document.getElementById('cell_border_color').value = 'B1B1B0';
    document.getElementById('week_days_cell_height').value = '50';
    document.getElementById('arrow_color_month').value = 'D1D1D1';
    document.getElementById('text_color_sun_days').value = '817F7F';
    document.getElementById('title_color').value = 'FFFFFF';
    document.getElementById('next_prev_event_bgcolor').value = '51004E';
    document.getElementById('title_font_size').value = '';
    document.getElementById('title_font').value = '';
    document.getElementById('title_style').value = 'normal';
    document.getElementById('date_color').value = 'FFFFFF';
    document.getElementById('date_size').value = '';
    document.getElementById('date_font').value = '';
    document.getElementById('date_style').value = 'normal';
    document.getElementById('popup_width').value = '800';
    document.getElementById('popup_height').value = '500';
    document.getElementById('number_of_shown_evetns').value = '2';
    document.getElementById('sundays_font_size').value = '25';
    document.getElementById('other_days_font_size').value = '25';
    document.getElementById('weekdays_font_size').value = '20';
    document.getElementById('border_width').value = '0';
    document.getElementById('top_height').value = '100';
    document.getElementById('bg_color_other_months').value = 'E1DDE9';
    document.getElementById('sundays_bg_color').value = 'E1E1E1';
    document.getElementById('weekdays_bg_color').value = 'E1E1E1';
    document.getElementById('week_start_day').value = 'su';
    document.getElementById('weekday_sunday_bg_color').value = 'BBBBBB';
    document.getElementById('border_radius').value = '0';
    document.getElementById('month_font_size').value = '35';
    document.getElementById('arrow_size').value = '45';
    document.getElementById('date_format').value = 'w/d/m/y';
    document.getElementById('date_bg_color').value = 'D6D5D5';
    document.getElementById('event_bg_color1').value = 'E1E1E1';
    document.getElementById('event_bg_color2').value = 'DEDDDD';
    document.getElementById('event_num_bg_color1').value = '420040';
    document.getElementById('event_num_bg_color2').value = '52004F';
    document.getElementById('event_num_color').value = 'FFFFFF';
    document.getElementById('day_month_font_color').value = '52004F';
    document.getElementById('week_font_color').value = '480045';
    document.getElementById('date_font_size').value = '15';
    document.getElementById('event_num_font_size').value = '13';
    document.getElementById('event_table_height').value = '30';
    document.getElementById('date_height').value = '25';
    document.getElementById('day_month_font_size').value = '12';
    document.getElementById('week_font_size').value = '15';
    document.getElementById('ev_title_bg_color').value = 'C5B1C4';
    document.getElementById('views_tabs_bg_color').value = '850088';
	document.getElementById('ev_title_bg_color').value = 'C5B1C4';
	document.getElementById('views_tabs_text_color').value = 'FFFFFF';
	document.getElementById('views_tabs_font_size').value = '13';
	document.getElementById("show_time1").checked = true;
	document.getElementById("show_cat1").checked = true;
	document.getElementById("show_event1").checked = true;
	document.getElementById("show_repeat1").checked = true;
    change_width();
  }
}

function reset_theme_0() {
  document.getElementById('width').value = '';
  document.getElementById('cell_height').value = '';
  document.getElementById('bg_top').value = 'FFFFFF';
  document.getElementById('bg_bottom').value = 'FFFFFF';
  document.getElementById('border_color').value = 'FFFFFF';
  document.getElementById('text_color_month').value = 'FFFFFF';
  document.getElementById('text_color_week_days').value = 'FFFFFF';
  document.getElementById('text_color_other_months').value = 'FFFFFF';
  document.getElementById('text_color_this_month_unevented').value = 'FFFFFF';
  document.getElementById('text_color_this_month_evented').value = 'FFFFFF';
  document.getElementById('event_title_color').value = 'FFFFFF';
  document.getElementById('current_day_border_color').value = 'FFFFFF';
  document.getElementById('bg_color_this_month_evented').value = 'FFFFFF';
  document.getElementById('next_prev_event_arrowcolor').value = 'FFFFFF';
  document.getElementById('show_event_bgcolor').value = 'FFFFFF';
  document.getElementById('cell_border_color').value = 'FFFFFF';
  document.getElementById('week_days_cell_height').value = '25';
  document.getElementById('arrow_color_month').value = 'FFFFFF';
  document.getElementById('text_color_sun_days').value = 'FFFFFF';
  document.getElementById('title_color').value = 'FFFFFF';
  document.getElementById('next_prev_event_bgcolor').value = 'FFFFFF';
  document.getElementById('title_font_size').value = '';
  document.getElementById('title_font').value = '';
  document.getElementById('title_style').value = '';
  document.getElementById('date_color').value = 'FFFFFF';
  document.getElementById('date_size').value = '';
  document.getElementById('date_font').value = '';
  document.getElementById('date_style').value = '';
  document.getElementById('popup_width').value = '';
  document.getElementById('popup_height').value = '';
  document.getElementById('number_of_shown_evetns').value = '';
  document.getElementById('sundays_font_size').value = '';
  document.getElementById('other_days_font_size').value = '';
  document.getElementById('weekdays_font_size').value = '';
  document.getElementById('border_width').value = '';
  document.getElementById('top_height').value = '';
  document.getElementById('bg_color_other_months').value = 'FFFFFF';
  document.getElementById('sundays_bg_color').value = 'FFFFFF';
  document.getElementById('weekdays_bg_color').value = 'FFFFFF';
  document.getElementById('week_start_day').value = '';
  document.getElementById('weekday_sunday_bg_color').value = 'FFFFFF';
  document.getElementById('border_radius').value = '';
  document.getElementById('month_font_size').value = '';
  document.getElementById('arrow_size').value = '';
  document.getElementById('date_format').value = 'w/d/m/y';
  document.getElementById('views_tabs_bg_color').value = 'FFFFFF';
  document.getElementById("show_time1").checked = true;
  document.getElementById("show_cat1").checked = true;
  document.getElementById("show_event1").checked = true;
  document.getElementById("show_repeat1").checked = true;
  change_width();
}


function set_theme() {
  var themeID = document.getElementById('slect_theme').value;
  switch (themeID) {
    case '0':
      reset_theme_0();
      break;

    case '1':
      reset_theme_1();
      break;

    case '2':
      reset_theme_2();
      break;

    case '3':
      reset_theme_3();
      break;

    case '4':
      reset_theme_4();
      break;

    case '5':
      reset_theme_5();
      break;

    case '6':
      reset_theme_6();
      break;

    case '7':
      reset_theme_7();
      break;

    case '8':
      reset_theme_8();
      break;

    case '9':
      reset_theme_9();
      break;

    case '10':
      reset_theme_10();
      break;

    case '11':
      reset_theme_11();
      break;

    case '12':
      reset_theme_12();
      break;

    case '13':
      reset_theme_13();
      break;

    case '14':
      reset_theme_14();
      break;

    case '15':
      reset_theme_15();
      break;

    case '16':
      reset_theme_16();
      break;

    case '17':
      reset_theme_17();
      break;
  }
  change_width();
}